shell = "zsh"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
rev = "v1.1.0"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
rev = "0.35.0"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
rev = "v0.7.1"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
rev = "v1.56"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
rev = "v0.9.8"
